import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Director X Cut is rebranded, multitrack, local-draft-only, and keeps upstream attribution", async () => {
  const html = await readFile(new URL("../app/opencut-editor.html", import.meta.url), "utf8");
  const script = await readFile(new URL("../app/opencut-editor.js", import.meta.url), "utf8");
  assert.match(html, /Director X Cut/);
  assert.match(html, /OpenCut Classic/);
  assert.match(html, /MIT/);
  assert.match(html, /不覆盖原始媒体/);
  assert.match(html, /原生 request_user_input/);
  assert.match(html, /VIDEO 1/);
  assert.match(html, /AUDIO 1/);
  assert.match(html, /CAPTIONS/);
  assert.match(html, /opencut-editor\.js/);
  assert.match(script, /\/directorx\/api\/editor-draft/);
  assert.match(script, /function compactOperations/);
  assert.match(script, /function undo/);
  assert.match(script, /function redo/);
  assert.match(script, /function applyTransition/);
  assert.match(script, /function applyCrop/);
  assert.match(script, /function applyDuck/);
  assert.match(script, /operation: "transition"/);
  assert.match(script, /operation: "crop"/);
  assert.match(script, /operation: "audio_duck"/);
  assert.match(script, /waveform\.peaks/);
  assert.match(script, /state\.waveformDescriptor\.endpoint/);
  assert.match(script, /function waveformViewportPlan/);
  assert.match(script, /waveformRequest/);
  assert.match(script, /state\.waveformCache/);
  assert.match(script, /data\.draft\?\.operations/);
  assert.match(script, /\/directorx\/api\/surface-heartbeat/);
  assert.match(script, /surface: "editor"/);
  assert.match(script, /const claimToken = surfaceParams\.get\("claim"\)/);
  assert.match(script, /X-DirectorX-Claim/);
  assert.match(script, /claimToken, surface: "editor"/);
  assert.match(script, /surfaceUrl\("\/directorx\/api\/editor-media"/);
  assert.match(script, /visibilitychange/);
  assert.match(script, /pagehide/);
  assert.doesNotMatch(html, /OpenCut Logo/);
  assert.doesNotMatch(html, /forcedOutputWatermark\s*:\s*true/);
  assert.doesNotThrow(() => new Function(script));
});
